In [74]:
import pandas as pd

In [75]:
df = pd.read_csv("Bengaluru_House_Data.csv")

In [76]:
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [77]:
df.columns

Index(['area_type', 'availability', 'location', 'size', 'society',
       'total_sqft', 'bath', 'balcony', 'price'],
      dtype='object')

In [78]:
df2 = df.drop(['area_type','availability','society','balcony'], axis = 'columns')

In [79]:
df2.head()

                   location       size total_sqft  bath   price
0  Electronic City Phase II      2 BHK       1056   2.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00
2               Uttarahalli      3 BHK       1440   2.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00
4                  Kothanur      2 BHK       1200   2.0   51.00

In [80]:
df2.isnull().sum()

location       1
size          16
total_sqft     0
bath          73
price          0
dtype: int64

In [81]:
df3 = df2.dropna()

In [82]:
df3.isnull().sum()

location      0
size          0
total_sqft    0
bath          0
price         0
dtype: int64

In [83]:
df3.head()

                   location       size total_sqft  bath   price
0  Electronic City Phase II      2 BHK       1056   2.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00
2               Uttarahalli      3 BHK       1440   2.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00
4                  Kothanur      2 BHK       1200   2.0   51.00

In [84]:
df3['size'].unique()

array(['2 BHK', '4 Bedroom', '3 BHK', '4 BHK', '6 Bedroom', '3 Bedroom',
       '1 BHK', '1 RK', '1 Bedroom', '8 Bedroom', '2 Bedroom',
       '7 Bedroom', '5 BHK', '7 BHK', '6 BHK', '5 Bedroom', '11 BHK',
       '9 BHK', '9 Bedroom', '27 BHK', '10 Bedroom', '11 Bedroom',
       '10 BHK', '19 BHK', '16 BHK', '43 Bedroom', '14 BHK', '8 BHK',
       '12 Bedroom', '13 BHK', '18 Bedroom'], dtype=object)

In [85]:
df3['bhk'] = df3['size'].apply(lambda x: int(x.split(' ')[0]))

/var/folders/vt/cn6qrdls5nl27cm7rkrwdb3m0000gn/T/ipykernel_94413/2222900254.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['bhk'] = df3['size'].apply(lambda x: int(x.split(' ')[0]))

In [86]:
df3.head()

                   location       size total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK       1056   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00    4
2               Uttarahalli      3 BHK       1440   2.0   62.00    3
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00    3
4                  Kothanur      2 BHK       1200   2.0   51.00    2

In [87]:
df3.total_sqft.unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      shape=(2067,), dtype=object)

In [102]:
def cal_space(x):
    value = x.split('-')
    if len(value) == 2:
        return (float(value[0])+float(value[1]))/2
    try:
        return float(x)
    except:
        return None

In [103]:
df3['total_sqft'] = df3['total_sqft'].apply(cal_space)

/var/folders/vt/cn6qrdls5nl27cm7rkrwdb3m0000gn/T/ipykernel_94413/1349617069.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['total_sqft'] = df3['total_sqft'].apply(cal_space)

In [104]:
df3.loc[30]

location      Yelahanka
size              4 BHK
total_sqft       2475.0
bath                4.0
price             186.0
bhk                   4
Name: 30, dtype: object

In [105]:
df4 = df3.copy()

In [106]:
df4.head()

                   location       size  total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK      1056.0   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom      2600.0   5.0  120.00    4
2               Uttarahalli      3 BHK      1440.0   2.0   62.00    3
3        Lingadheeranahalli      3 BHK      1521.0   3.0   95.00    3
4                  Kothanur      2 BHK      1200.0   2.0   51.00    2

In [107]:

df4['cost_per_sqft'] = (df4['price'] * 1000000) / df4['total_sqft']

df4.head()

,location,size,total_sqft,bath,price,bhk,cost_per_sqft
0,Electronic City Phase II,2 BHK,1056.0,2.0,39.07,2,36998.106061
1,Chikka Tirupathi,4 Bedroom,2600.0,5.0,120.00,4,46153.846154
2,Uttarahalli,3 BHK,1440.0,2.0,62.00,3,43055.555556
3,Lingadheeranahalli,3 BHK,1521.0,3.0,95.00,3,62458.908613
4,Kothanur,2 BHK,1200.0,2.0,51.00,2,42500.000000

In [114]:
df4.location.unique()

array(['Electronic City Phase II', 'Chikka Tirupathi', 'Uttarahalli',
       'Lingadheeranahalli', 'Kothanur', 'Whitefield', 'Old Airport Road',
       'Rajaji Nagar', 'Marathahalli', 'other', '7th Phase JP Nagar',
       'Gottigere', 'Sarjapur', 'Mysore Road', 'Bisuvanahalli',
       'Raja Rajeshwari Nagar', 'Kengeri', 'Binny Pete', 'Thanisandra',
       'Bellandur', ' Thanisandra', 'Electronic City', 'Ramagondanahalli',
       'Yelahanka', 'Hebbal', 'Kasturi Nagar', 'Kanakpura Road',
       'Electronics City Phase 1', 'Kundalahalli', 'Chikkalasandra',
       'Murugeshpalya', 'Sarjapur  Road', 'Ganga Nagar', 'HSR Layout',
       'Doddathoguru', 'KR Puram', 'Bhoganhalli', 'Lakshminarayana Pura',
       'Begur Road', 'Varthur', 'Bommanahalli', 'Gunjur',
       'Devarachikkanahalli', 'Hegde Nagar', 'Haralur Road',
       'Hennur Road', 'Kothannur', 'Kalena Agrahara', 'Kaval Byrasandra',
       'ISRO Layout', 'Garudachar Palya', 'EPIP Zone', 'Dasanapura',
       'Kasavanhalli', 'Sanjay nagar', ' Mysore Highway', 'Domlur',
       'Sarjapura - Attibele Road', 'Yeshwanthpur', 'Chandapura',
       'Nagarbhavi', 'Devanahalli', 'Ramamurthy Nagar', 'Malleshwaram',
       'Akshaya Nagar', 'Shampura', 'Kadugodi', 'LB Shastri Nagar',
       'Hormavu', 'Vishwapriya Layout', 'Kudlu Gate',
       '8th Phase JP Nagar', 'Bommasandra Industrial Area', 'Anandapura',
       'Vishveshwarya Layout', 'Kengeri Satellite Town', 'Kannamangala',
       ' Devarachikkanahalli', 'Hulimavu', 'Mahalakshmi Layout',
       'Hosa Road', 'Attibele', 'CV Raman Nagar', 'Kumaraswami Layout',
       'Nagavara', 'Hebbal Kempapura', 'Vijayanagar',
       'Pattandur Agrahara', 'Nagasandra', 'Kogilu', 'Panathur',
       'Padmanabhanagar', '1st Block Jayanagar', 'Kammasandra',
       'Off Sarjapur Road, ', 'Dasarahalli', 'Magadi Road', 'Koramangala',
       'Dommasandra', 'Budigere', 'Kalyan nagar', 'OMBR Layout',
       'Horamavu Agara', 'Ambedkar Nagar', 'Talaghattapura', 'Balagere',
       'Jigani', 'Gollarapalya Hosahalli', 'Old Madras Road',
       'Kaggadasapura', '9th Phase JP Nagar', 'Jakkur', 'TC Palaya',
       'Giri Nagar', 'Singasandra', 'AECS Layout', 'Mallasandra', 'Begur',
       'JP Nagar', 'Malleshpalya', 'Munnekollal', 'Kaggalipura',
       '6th Phase JP Nagar', 'Ulsoor', 'Thigalarapalya',
       'Somasundara Palya', 'Basaveshwara Nagar', 'Bommasandra',
       'Ardendale', 'Harlur', 'Kodihalli', 'Narayanapura',
       'Bannerghatta Road', 'Hennur', '5th Phase JP Nagar', 'Kodigehaali',
       'Billekahalli', 'Jalahalli', 'Mahadevpura', 'Anekal',
       'Hoodi Circle, ', 'Sompura', 'Dodda Nekkundi', 'Hosur Road',
       'Battarahalli', 'Sultan Palaya', 'Ambalipura', 'Hoodi',
       'Brookefield', 'Yelenahalli', 'Vittasandra',
       '2nd Stage Nagarbhavi', 'Vidyaranyapura', 'Amruthahalli',
       'Kodigehalli', 'Subramanyapura', 'Basavangudi', 'Kenchenahalli',
       'Banjara Layout', 'Kereguddadahalli', 'Kambipura',
       'Banashankari Stage III', 'Sector 7 HSR Layout',
       'Yemlur, Old Airport Road, ', 'Rajiv Nagar', 'Arekere',
       'Mico Layout', 'Kammanahalli', 'Banashankari', 'Chikkabanavar',
       'HRBR Layout', 'Nehru Nagar', 'Kanakapura', 'Konanakunte',
       'Margondanahalli', 'R.T. Nagar', 'Tumkur Road', 'Vasanthapura',
       'GM Palaya', 'Jalahalli East', 'Hosakerehalli', 'Indira Nagar',
       'Kodichikkanahalli', 'Varthur Road', 'Anjanapura', 'Abbigere',
       'Tindlu', 'Gubbalala', 'Dairy Circle', 'Parappana Agrahara',
       'Cunningham Road', 'Kudlu', 'Banashankari Stage VI', 'Cox Town',
       'Kathriguppe', 'HBR Layout', 'Yelahanka New Town',
       'Sahakara Nagar', 'Rachenahalli', 'Sadashiva Nagar',
       'Yelachenahalli', 'Green Glen Layout', 'Thubarahalli',
       'Naganathapura', 'Horamavu Banaswadi', '1st Phase JP Nagar',
       'NGR Layout', 'Seegehalli', 'BEML Layout', 'NRI Layout', 'ITPL',
       'Babusapalaya', 'Nagappa Reddy Layout', 'BTM 1st Stage',
       'Iblur Village', 'Ananth Nagar', 'Basapura', 'Channasandra',
       'Sector 1 HSR Layout', 'Choodasandra', 'Kaikondrahalli',
       'Neeladri Nagar', 'Frazer Town', 'Cooke Town', 'Doddakallasandra',
       'Chamrajpet', 'Rayasandra', 'Kalkere', '5th Block Hbr Layout',
       'Pai Layout', 'Banashankari Stage V', 'Sonnenahalli',
       'ECC Road, Whitefield, ', 'Benson Town',
       '2nd Phase Judicial Layout', 'Sarjapur Road, ',
       'Poorna Pragna Layout', 'Judicial Layout', 'Varthur Road, ',
       'Banashankari Stage II', 'Karuna Nagar', 'Bannerghatta', 'Marsur',
       'Bommenahalli', 'Laggere', 'Prithvi Layout', 'Banaswadi',
       'Sector 2 HSR Layout', 'Shivaji Nagar', 'Badavala Nagar',
       'Nagavarapalya', 'BTM Layout', 'BTM 2nd Stage',
       '1st Block Koramangala', 'Hoskote', 'Doddaballapur',
       'Gunjur Palya', 'Sarakki Nagar', 'Thyagaraja Nagar',
       'Bharathi Nagar', ' ittamadu', 'Thanisandra Main Road, ',
       ' Bhoganhalli', ' Anekal', 'Dodsworth Layout', 'Kudlu Village, ',
       'Banaswadi, ', 'HAL 2nd Stage', ' Devarabeesana Halli',
       ' Rachenahalli', 'Kadubeesanahalli', 'Off Sarjapur road, ',
       'Nagadevanahalli', 'JP Nagar 8th Phase, ', 'JP nagar 9th Phase, ',
       'Near Electronic City, ', 'JP Nagar 7th Phase, ',
       ' Electronic City', 'Whitefield, ', ' Whitefield', 'Bellandur, ',
       ' south', 'Judicial Layout, Kanakapura Road, ', 'Whietfield, ',
       ' Basavangudi', ' Sector 1 HSR Layout',
       'Electronic city Phase 1, ', ' Banaswadi',
       'HSR Layout 7th sector, ', 'Jayanagar, ', 'Haralur Road, ',
       'Panathur Road, ', 'Electronic city phase 1, ', 'Banasawadi, ',
       'Kanakapura Road, ', 'Electronic City Phase 1, '], dtype=object)

In [115]:
df4.location = df4.location.apply(lambda x: x.strip())

In [116]:
location_stats = df4.groupby('location')['location'].agg('count').sort_values(ascending=False)
location_stats.head(30)

location
other                       2683
Whitefield                   535
Sarjapur  Road               392
Electronic City              304
Kanakpura Road               266
Thanisandra                  236
Yelahanka                    210
Uttarahalli                  186
Hebbal                       176
Marathahalli                 175
Raja Rajeshwari Nagar        171
Bannerghatta Road            152
Hennur Road                  150
7th Phase JP Nagar           149
Haralur Road                 141
Electronic City Phase II     131
Rajaji Nagar                 106
Chandapura                    98
Bellandur                     96
Hoodi                         88
KR Puram                      88
Electronics City Phase 1      87
Yeshwanthpur                  85
Begur Road                    84
Sarjapur                      81
Harlur                        79
Kasavanhalli                  79
Banashankari                  74
Hormavu                       74
Kengeri                       73
Name: location, dtype: int64

In [117]:
len(location_stats[location_stats<10])

31

In [118]:
location_stats_less_that_10 = location_stats[location_stats<10]
location_stats_less_that_10

location
Sarjapur Road,                       8
Hoodi Circle,                        7
Devarabeesana Halli                  6
Off Sarjapur Road,                   5
Judicial Layout, Kanakapura Road,    4
Mysore Highway                       4
Thanisandra Main Road,               3
Varthur Road,                        2
Whitefield,                          2
JP Nagar 7th Phase,                  2
south                                2
Electronic city Phase 1,             2
JP Nagar 8th Phase,                  2
ECC Road, Whitefield,                2
Bellandur,                           1
Haralur Road,                        1
ittamadu                             1
HSR Layout 7th sector,               1
Yemlur, Old Airport Road,            1
JP nagar 9th Phase,                  1
Panathur Road,                       1
Electronic city phase 1,             1
Jayanagar,                           1
Kanakapura Road,                     1
Kudlu Village,                       1
Whietfield,                          1
Banasawadi,                          1
Electronic City Phase 1,             1
Off Sarjapur road,                   1
Banaswadi,                           1
Near Electronic City,                1
Name: location, dtype: int64

In [119]:
df4.location = df4.location.apply(lambda x: 'other' if x in location_stats_less_that_10 else x)
len(df4.location.unique())

255

In [120]:
df4.head(10)

,location,size,total_sqft,bath,price,bhk,cost_per_sqft
0,Electronic City Phase II,2 BHK,1056.0,2.0,39.07,2,36998.106061
1,Chikka Tirupathi,4 Bedroom,2600.0,5.0,120.00,4,46153.846154
2,Uttarahalli,3 BHK,1440.0,2.0,62.00,3,43055.555556
3,Lingadheeranahalli,3 BHK,1521.0,3.0,95.00,3,62458.908613
4,Kothanur,2 BHK,1200.0,2.0,51.00,2,42500.000000
5,Whitefield,2 BHK,1170.0,2.0,38.00,2,32478.632479
6,Old Airport Road,4 BHK,2732.0,4.0,204.00,4,74670.571010
7,Rajaji Nagar,4 BHK,3300.0,4.0,600.00,4,181818.181818
8,Marathahalli,3 BHK,1310.0,3.0,63.25,3,48282.442748
9,other,6 Bedroom,1020.0,6.0,370.00,6,362745.098039