In [1]:
import pandas as pd

In [5]:
df = pd.read_csv("Bengaluru_House_Data.csv")

In [6]:
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [13]:
df.columns

Index(['area_type', 'availability', 'location', 'size', 'society',
       'total_sqft', 'bath', 'balcony', 'price'],
      dtype='object')

In [19]:
df2 = df.drop(['area_type','availability','society','balcony'], axis = 'columns')

In [20]:
df2.head()

                   location       size total_sqft  bath   price
0  Electronic City Phase II      2 BHK       1056   2.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00
2               Uttarahalli      3 BHK       1440   2.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00
4                  Kothanur      2 BHK       1200   2.0   51.00

In [21]:
df2.isnull().sum()

location       1
size          16
total_sqft     0
bath          73
price          0
dtype: int64

In [22]:
df3 = df2.dropna()

In [24]:
df3.isnull().sum()

location      0
size          0
total_sqft    0
bath          0
price         0
dtype: int64

In [25]:
df3.head()

                   location       size total_sqft  bath   price
0  Electronic City Phase II      2 BHK       1056   2.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00
2               Uttarahalli      3 BHK       1440   2.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00
4                  Kothanur      2 BHK       1200   2.0   51.00

In [26]:
df3['size'].unique()

array(['2 BHK', '4 Bedroom', '3 BHK', '4 BHK', '6 Bedroom', '3 Bedroom',
       '1 BHK', '1 RK', '1 Bedroom', '8 Bedroom', '2 Bedroom',
       '7 Bedroom', '5 BHK', '7 BHK', '6 BHK', '5 Bedroom', '11 BHK',
       '9 BHK', '9 Bedroom', '27 BHK', '10 Bedroom', '11 Bedroom',
       '10 BHK', '19 BHK', '16 BHK', '43 Bedroom', '14 BHK', '8 BHK',
       '12 Bedroom', '13 BHK', '18 Bedroom'], dtype=object)

In [27]:
df3['bhk'] = df3['size'].apply(lambda x: int(x.split(' ')[0]))

/var/folders/vt/cn6qrdls5nl27cm7rkrwdb3m0000gn/T/ipykernel_96104/2222900254.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['bhk'] = df3['size'].apply(lambda x: int(x.split(' ')[0]))

In [28]:
df3.head()

                   location       size total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK       1056   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00    4
2               Uttarahalli      3 BHK       1440   2.0   62.00    3
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00    3
4                  Kothanur      2 BHK       1200   2.0   51.00    2

In [33]:
df3.total_sqft.unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      shape=(2067,), dtype=object)

In [37]:
def cal_space(x):
    value = x.split('-')
    if len(value) == 2:
        return (float(value[0])+float(value[1]))/2
    try:
        return float(x)
    except:
        return None

In [41]:
df3.loc[30]

location      Yelahanka
size              4 BHK
total_sqft       2475.0
bath                4.0
price             186.0
bhk                   4
Name: 30, dtype: object

In [42]:
df4 = df3.copy()

In [43]:
df4.head()

                   location       size  total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK      1056.0   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom      2600.0   5.0  120.00    4
2               Uttarahalli      3 BHK      1440.0   2.0   62.00    3
3        Lingadheeranahalli      3 BHK      1521.0   3.0   95.00    3
4                  Kothanur      2 BHK      1200.0   2.0   51.00    2

In [53]:

df4['cost_per_sqft'] = (df4['price'] * 1000000) / df4['total_sqft']

df4.head()

,location,size,total_sqft,bath,price,bhk,cost_per_sqft
0,Electronic City Phase II,2 BHK,1056.0,2.0,39.07,2,36998.106061
1,Chikka Tirupathi,4 Bedroom,2600.0,5.0,120.00,4,46153.846154
2,Uttarahalli,3 BHK,1440.0,2.0,62.00,3,43055.555556
3,Lingadheeranahalli,3 BHK,1521.0,3.0,95.00,3,62458.908613
4,Kothanur,2 BHK,1200.0,2.0,51.00,2,42500.000000

In [56]:
df4.location.unique()

array(['Electronic City Phase II', 'Chikka Tirupathi', 'Uttarahalli', ...,
       '12th cross srinivas nagar banshankari 3rd stage',
       'Havanur extension', 'Abshot Layout'], shape=(1304,), dtype=object)

In [57]:
df4.location = df4.location.apply(lambda x: x.strip())

In [65]:
location_stats = df4.groupby('location')['location'].agg('count').sort_values(ascending=False)
location_stats.head(30)

location
other                       2716
Whitefield                   535
Sarjapur  Road               392
Electronic City              304
Kanakpura Road               266
Thanisandra                  236
Yelahanka                    210
Uttarahalli                  186
Hebbal                       176
Marathahalli                 175
Raja Rajeshwari Nagar        171
Bannerghatta Road            152
Hennur Road                  150
7th Phase JP Nagar           149
Haralur Road                 141
Electronic City Phase II     131
Rajaji Nagar                 106
Chandapura                    98
Bellandur                     96
Hoodi                         88
KR Puram                      88
Electronics City Phase 1      87
Yeshwanthpur                  85
Begur Road                    84
Sarjapur                      81
Harlur                        79
Kasavanhalli                  79
Hormavu                       74
Banashankari                  74
Ramamurthy Nagar              73
Name: location, dtype: int64

In [66]:
len(location_stats[location_stats<10])

30

In [67]:
location_stats_less_that_10 = location_stats[location_stats<10]
location_stats_less_that_10

location
Sarjapur Road,                       8
Hoodi Circle,                        7
Off Sarjapur Road,                   5
Judicial Layout, Kanakapura Road,    4
Mysore Highway                       4
Thanisandra Main Road,               3
ECC Road, Whitefield,                2
Whitefield,                          2
Varthur Road,                        2
south                                2
JP Nagar 7th Phase,                  2
Electronic city Phase 1,             2
JP Nagar 8th Phase,                  2
ittamadu                             1
Kudlu Village,                       1
Yemlur, Old Airport Road,            1
Electronic city phase 1,             1
HSR Layout 7th sector,               1
Haralur Road,                        1
Near Electronic City,                1
Jayanagar,                           1
Bellandur,                           1
Whietfield,                          1
Banasawadi,                          1
Off Sarjapur road,                   1
JP nagar 9th Phase,                  1
Banaswadi,                           1
Panathur Road,                       1
Electronic City Phase 1,             1
Kanakapura Road,                     1
Name: location, dtype: int64

In [68]:
df4.location = df4.location.apply(lambda x: 'other' if x in location_stats_less_that_10 else x)
len(df4.location.unique())

253

In [69]:
df4

,location,size,total_sqft,bath,price,bhk,cost_per_sqft
0,Electronic City Phase II,2 BHK,1056.0,2.0,39.07,2,36998.106061
1,Chikka Tirupathi,4 Bedroom,2600.0,5.0,120.00,4,46153.846154
2,Uttarahalli,3 BHK,1440.0,2.0,62.00,3,43055.555556
3,Lingadheeranahalli,3 BHK,1521.0,3.0,95.00,3,62458.908613
4,Kothanur,2 BHK,1200.0,2.0,51.00,2,42500.000000
...,...,...,...,...,...,...,...
13315,Whitefield,5 Bedroom,3453.0,4.0,231.00,5,66898.349262
13316,other,4 BHK,3600.0,5.0,400.00,4,111111.111111
13317,Raja Rajeshwari Nagar,2 BHK,1141.0,2.0,60.00,2,52585.451358
13318,Padmanabhanagar,4 BHK,4689.0,4.0,488.00,4,104073.363190
13319,Doddathoguru,1 BHK,550.0,1.0,17.00,1,30909.090909